version: '3.8'
services:
  app:
    container_name: EA-BackEnd
    restart: always
    build: .
    ports:
      - '5432:5432'
    links:
      - mongo
  mongo:
    container_name: EA-BackEnd-Mongo
    image: mongo
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      - backendDB:/data/db
  
volumes:
  backendDB:
